### ISSUE TITLE
Deadlock with multiple FFTW plan construction / destruction in serial and threaded runs

### ISSUE THREAD

**Issue by mfherbst** [JuliaMath/FFTW.jl#141] opened 2020-03-10 17:14 UTC
Running the following code example causes a deadlock conjunction with Julia 1.3.1, DFTK 0.0.5 and FFTW 1.2.0. [Stacktrace](https://gist.github.com/mfherbst/4015ff891001597fccf66648abff1aa1) (after a Ctrl-C) indicates that the deadlock occurs in fftw. Notice, such behaviour is encountered both in serial and threaded runs.

Code example:
```
using DFTK    
    
function main()    
    for Ecut in 0.0 .+ collect(3:20)    
        println("Ecut = $Ecut")    
        a = 10.263141334305942    
        lattice = a / 2 .* [[0 1 1.]; [1 0 1.]; [1 1 0.]]    
        model = Model(lattice; terms=[Kinetic()], n_electrons=4)    
        basis = PlaneWaveBasis(model, Ecut)    
    end    
end    
    
main()   
```

Output / Stacktrace: https://gist.github.com/mfherbst/4015ff891001597fccf66648abff1aa1

Sorry about the complicated reproducer btw ... I tried to reduce as much as I could.

**Comment by mfherbst** [comment] 2020-03-11 15:50
Note: The issue also present on master as of now.

**Comment by mfherbst** [comment] 2020-03-11 15:51
Could be related to #135.

**Comment by mfherbst** [comment] 2020-03-11 15:54
The issue disappears when setting explicitly `FFTW.set_num_threads(1)`.

**Comment by stevengj** [comment] 2020-03-11 16:00
@vtjnash, any ideas?   FFTW has an internal pthreads mutex lock around plan creation and destruction, but I don't see how that could deadlock Julia…

**Comment by EthanAnderes** [comment] 2020-03-26 22:56
I think I'm seeing the same issue. Here is a reduced toy case.```
using FFTW 
import Base: * 

struct rFFT{nᵢ} end

@generated function plan(::Type{F}) where {nᵢ, F<:rFFT{nᵢ}}
    X  = zeros(Float64, nᵢ...) 
    FT = plan_rfft(X; flags=FFTW.MEASURE, timelimit=10)
    return :( $FT )
end

nᵢ = (256, 50)
FT = rFFT{nᵢ}
matx = rand(Float64, nᵢ...)

plan(FT) * matx
```

The last line hangs with no CPU activity coming from Julia. If, however, I replace the 
last line with the following two lines 

```
*(::Type{FT}, x::Array) where FT<:rFFT = plan(FT) * x
FT * matx
```

then I get this segfault. 

```
julia> FT * matx

signal (11): Segmentation fault: 11
in expression starting at REPL[9]:1
spawn_apply at /Users/ethananderes/.julia/artifacts/686f343230e1853cc948cd0736b57067c66bca4b/lib/libfftw3.3.dylib (unknown line)
#1 at ./threadingconstructs.jl:126
unknown function (ip: 0x115f16cf4)
jl_apply at /Users/ethananderes/Software/juliaMaster/src/./julia.h:1685 [inlined]
start_task at /Users/ethananderes/Software/juliaMaster/src/task.c:687
Allocations: 7684063 (Pool: 7682495; Big: 1568); GC: 7
zsh: segmentation fault  /Users/ethananderes/Software/juliaMaster/julia -O3
```

I tried to track down the issue further but I hit my limit of understanding. Hope 
this helps.

```
julia> versioninfo()
Julia Version 1.5.0-DEV.513
Commit 5ecc17f0e0 (2020-03-26 20:16 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.4.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_FFTW_PROVIDER = FFTW
```

**Comment by mfherbst** [comment] 2020-03-27 08:46
I can reproduce your first example on Julia 1.4 and FFTW 1.2.0, but I do not get a segfault in your second example, only a hanging Julia process again.

As before a `FFTW.set_num_threads(1)` makes the code run through smoothly.

**Comment by EthanAnderes** [comment] 2020-03-27 17:03
Note: to get the seg fault I need to use a fresh session and not 
evaluate `plan(FT) * matx` first. 
```
using FFTW 
import Base: * 
struct rFFT{nᵢ} end
@generated function plan(::Type{F}) where {nᵢ, F<:rFFT{nᵢ}}
    X  = zeros(Float64, nᵢ...) 
    FT = plan_rfft(X; flags=FFTW.MEASURE, timelimit=10)
    return :( $FT )
end
nᵢ = (256, 50)
FT = rFFT{nᵢ}
matx = rand(Float64, nᵢ...)
*(::Type{FT}, x::Array) where FT<:rFFT = plan(FT) * x
FT * matx
```

on Julia v1.4.0 I don't get as much readout from the segfault:

```
julia> FT * matx
zsh: segmentation fault  /Users/ethananderes/Software/julia1.4/julia -O3
``` 
Perhaps I should also remark that by using a generated function for `plan`
I'm trying to memoize it for quick instantiation inside other functions. 
If anyone knows of a non-segfault way to get around this I'd love to hear it.

**Comment by vtjnash** [comment] 2020-03-27 17:22
Attempting to access FFTW inside `@generated` should be obviously invalid by the documentation for what is okay. If you want memoization, you should be writing your own, not trying to cause undefined behavior in the compiler. I suspect it should be trying to print that out as an error message, but I'm not certain why that fails.

**Comment by vtjnash** [comment] 2020-03-27 17:26
@stevengj It looks like it's possibly trying to recursively hold the lock, since it's in the middle of one plan and trying to finalize a different one. I'd like to move all finalizers to a separate thread to solve this issue, but that's it's rather far away on my roadmap right now. For now, I recommend only doing trivial things in a finalizer, like appending it to a queue to be cleaned up later.

**Comment by EthanAnderes** [comment] 2020-03-27 19:10
> FFTW inside `@generated`  should be obviously invalid by the documentation for what is okay.

I guess your referring to FFTW documentation that ftt plans have global mutable state? 
So that if, instead, they just where regular structs which held information on which 
fft method to apply then it would be fine?

Anyway, these generated functions for caching fft plans have been working flawlessly for me
for a number of years now and only started giving me problems with the new threading stuff.
(see [here](https://github.com/marius311/CMBLensing.jl/blob/d2651277b8b8fca3cd730c3894bc323f35bdd612/src/flat_fftgrid.jl#L35) for example)

**Comment by ianshmean** [comment] 2020-06-20 19:06
Has anyone found a workaround other than setting `set_num_threads(1)`? I'm guessing not, but thought I'd check given the performance hit

**Comment by ianshmean** [comment] 2020-06-21 14:20
@vtjnash if it's insightful at all, commenting out the finalizer here doesn't seem to change the seg fault
https://github.com/JuliaMath/FFTW.jl/blob/0745fe29921d35b815d64038598b33afa564e486/src/fft.jl#L244

**Comment by ianshmean** [comment] 2020-06-21 20:49
Ok, commenting out the finalizer fixes @mfherbst's main example with threaded FFTW

**Comment by stevengj** [comment] 2020-08-17 19:14
This issue should be fixed by #160.

**Comment by antoine-levitt** [comment] 2020-08-17 19:31
Great, thanks for the fix! Can't reproduce the original issue anymore on FFTW 1.2.2. I don't think we changed anything in DFTK in that respect, so the only difference seems to be that I'm running julia 1.5.

**Comment by mfherbst** [comment] 2020-08-18 06:00
@stevengj @vtjnash Thanks for the update and your effort on this stuff!

**Closed** 2020-08-20 02:13 UTC
