### ISSUE TITLE
FFTW could not create plan for `fft(n × m × 1 array, 2)`

### ISSUE THREAD

**Issue by EthanAnderes** [JuliaMath/FFTW.jl#142] opened 2020-03-13 12:02 UTC
With `ENV["JULIA_FFTW_PROVIDER"] = "MKL"` I get errors for ` fft` and ` rfft` of a `n × m × 1` array along dimension 2.

```
ENV["JULIA_FFTW_PROVIDER"] = "MKL"
using Pkg 
pkg"build FFTW"
using FFTW
v = rand(32,1)
m = rand(32,32,1)
fft(v,1) #<- works fine
fft(m,2) #<- ERROR
```

Here is the output I get 

```
julia> fft(m,2) #<- ERROR
ERROR: FFTW could not create plan
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] FFTW.cFFTWPlan{Complex{Float64},-1,false,3}(::Array{Complex{Float64},3}, ::FFTW.FakeArray{Complex{Float64},3}, ::Int64, ::UInt32, ::Float64) at /Users/ethananderes/.julia/packages/FFTW/qqcBj/src/fft.jl:507
 [3] plan_fft(::Array{Complex{Float64},3}, ::Int64; flags::UInt32, timelimit::Float64) at /Users/ethananderes/.julia/packages/FFTW/qqcBj/src/fft.jl:619
 [4] plan_fft at /Users/ethananderes/.julia/packages/FFTW/qqcBj/src/fft.jl:619 [inlined]
 [5] fft(::Array{Complex{Float64},3}, ::Int64) at /Users/ethananderes/.julia/packages/AbstractFFTs/mhQvY/src/definitions.jl:51
 [6] fft(::Array{Float64,3}, ::Int64) at /Users/ethananderes/.julia/packages/AbstractFFTs/mhQvY/src/definitions.jl:198
 [7] top-level scope at REPL[8]:1
```

Note: with `ENV["JULIA_FFTW_PROVIDER"] = "FFTW"` everything works fine. 

```
ENV["JULIA_FFTW_PROVIDER"] = "FFTW"
using Pkg 
pkg"build FFTW"
using FFTW
v = rand(32,1)
m = rand(32,32,1)
fft(v,1) #<- works fine
fft(m,2) #<- works fine
```

**Comment by stevengj** [comment] 2022-10-08 00:51
Duplicate of #242.  Use the real FFTW library, and complain to Intel.

**Closed by stevengj** 2022-10-08 00:51 UTC
