### ISSUE TITLE
FFTW hangs when planning multiple transforms

### ISSUE THREAD

**Issue by aplavin** [JuliaMath/FFTW.jl#155] opened 2020-06-02 21:36 UTC
I noticed several other issues about FFTW hanging when either some racing condition happens, or in some fancy `@generated` or template code. However, my example does not have any of those, and may have a different cause. Multithreading is present here as well, though.

When I run this code:
```julia
using FFTW

FFTW.set_num_threads(3)
for i in [8, 16, 32, 64, 100, 128, 256, 500, 640, 1280] #|> reverse
    @show i
    a = zeros(i, i)
    @show size(a)
    p = plan_rfft(a, flags=FFTW.MEASURE)
    @show size(p)
end
```
julia hangs without any CPU activity after printing `size(a) = (640, 640)` - so, in the `plan_rfft` function. After interrupting it gives a very long stacktrace, the last lines are the following:
```
fftw_mkapiplan at /home/aplavin/.julia/artifacts/91707ee1baf86e9f971d587e5379ee3956a7c5e0/lib/libfftw3.so (unknown line)
fftw_plan_guru64_dft_r2c at /home/aplavin/.julia/artifacts/91707ee1baf86e9f971d587e5379ee3956a7c5e0/lib/libfftw3.so (unknown line)
rFFTWPlan at /home/aplavin/.julia/packages/FFTW/5DZuu/src/fft.jl:519
unknown function (ip: 0x7f2a74a3e2ab)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
#plan_rfft#19 at /home/aplavin/.julia/packages/FFTW/5DZuu/src/fft.jl:672
plan_rfft##kw at /home/aplavin/.julia/packages/FFTW/5DZuu/src/fft.jl:670 [inlined]
#plan_rfft#21 at /home/aplavin/.julia/packages/FFTW/5DZuu/src/fft.jl:694 [inlined]
plan_rfft##kw at /home/aplavin/.julia/packages/FFTW/5DZuu/src/fft.jl:694 [inlined]
top-level scope at /home/aplavin/work/work/julia/tmp.jl:8
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:813
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:872
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:877
include at ./Base.jl:377
exec_options at ./client.jl:288
_start at ./client.jl:484
jfptr__start_2075.clone_1 at /home/aplavin/julia-1.4.2/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
unknown function (ip: 0x401931)
unknown function (ip: 0x401533)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4015d4)
unknown function (ip: (nil))
Allocations: 4645100 (Pool: 4644194; Big: 906); GC: 6
```
Note that the issue is not due to some specific size not working: i.e. if I uncomment the `reverse` part, the script successfully finishes. But if the number of threads is set to 4, then the reversed order also hangs.

Any idea why this may happen?

**Comment by giordano** [comment] 2020-06-02 22:10
Is this with `JULIA_NUM_THREADS=1`?  I've also been experiencing similar issues as this one, but never managed to reduce to a small example starting from my bigger problem.

**Comment by aplavin** [comment] 2020-06-02 22:14
I definitely want to use multiple threads for FFT computations - it scales pretty well to ~10 cores I have.

Interesting note about `JULIA_NUM_THREADS` however: if I set it to one the code no longer hangs! This seems really strange for me, because there is no julia-level threading in the code anyway. And I cannot easily give up on julia multithreading as well: while I call FFTs from a single julia thread, other parts of my code/script do use multhreading.

**Comment by giordano** [comment] 2020-06-02 22:20
> Interesting note about JULIA_NUM_THREADS however: if I set it to one the code no longer hangs! This seems really strange for me, because there is no julia-level threading in the example anyway.

This is my experience as well

**Comment by antoine-levitt** [comment] 2020-06-05 10:48
I think this is the same as https://github.com/JuliaMath/FFTW.jl/issues/141

**Comment by giordano** [comment] 2020-06-05 10:56
Right.  I'm closing this as duplicate of #141

**Closed by giordano** 2020-06-05 10:56 UTC
