### ISSUE TITLE
Darwin ARM: libfftw3 not defined

### ISSUE THREAD

**Issue by lukeburns** [JuliaMath/FFTW.jl#187] opened 2021-03-17 22:01 UTC
Running native Julia, version 1.7.0-DEV on Mac M1

```jl
julia> versioninfo()
Julia Version 1.7.0-DEV.720
Commit 5515893eac (2021-03-17 18:47 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cyclone)

julia> using FFTW
[ Info: Precompiling FFTW [7a1cc6ca-52ef-59f5-83cd-3a7055c09341]
ERROR: LoadError: UndefVarError: libfftw3 not defined
```

I tried [adding `FFTW_jll`](https://github.com/JuliaMath/FFTW.jl/issues/143) with no dice

**Comment by giordano** [comment] 2021-03-17 22:45
Yes, all JLL packages won't work on aarch64 Darwin at the moment

**Comment by giordano** [comment] 2021-03-17 23:58
@lukeburns I've built FFTW for aarch64-apple-darwin, you can test it with
```julia
]add https://github.com/giordano/FFTW_jll.jl.git
```

_**NOTE**_: this is meant to be a test, the "official" build will come at some point in the future.  Also, I'm not going to do this kind of builds for other libraries, but it'd be good to get some feedback on this one before the official rollout.

**Comment by lukeburns** [comment] 2021-03-18 00:07
Works for me!

**Comment by giordano** [comment] 2021-03-18 00:31
@lukeburns thanks for confirmation!  To be clear, it's useless to go around to report the lack of `aarch64-apple-darwin`: all binaries are built in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) and we already know well the situation.  The problem is that the presence of binaries for the new platform implies requiring Julia v1.6+: we simply can't cut out all already released Julia versions for all binaries.

**Comment by lukeburns** [comment] 2021-03-18 00:43
@giordano Aha, I was just about to ask — just found Yggdrasil. So it's a matter of distribution, rather than a technical issue? Does this mean I should be able to manually build any JLL package locally?

**Comment by giordano** [comment] 2021-03-18 00:46
> @giordano Aha, I was just about to ask — just found Yggdrasil. So it's a matter of distribution, rather than a technical issue?

Yes, exactly.

> Does this mean I should be able to manually build any JLL package locally?

In principle yes, using [BinaryBuilder](https://binarybuilder.org/)

**Comment by giordano** [comment] 2021-04-02 19:03
Meta issue about building JLL packages for the new platform: https://github.com/JuliaPackaging/Yggdrasil/issues/2763.

**Comment by cadojo** [comment] 2021-07-12 03:19
I noticed `FFTW` now requires Julia `v1.6`, and @giordano's experimental `aarch64-apple-darwin` fork seems to have been added to `FFTW_jll`. Is there a new status for `apple-darwin` support for `FFTW`? Definitely not trying to rush anyone, just curious on the status since the two "issues" listed on the `FFTW` line in JuliaPackaging/Yggdrasil#2763 seem to be implemented already.

**Comment by giordano** [comment] 2021-10-12 23:17
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/3585

**Closed by giordano** 2021-10-12 23:17 UTC

**Comment by xiang-yu** [comment] 2023-07-02 20:10
Hi everyone,

I've got the following error when installing the "**FFTW**" package with Julia version **1.9.1** on **M2 Max** chip with **Ventura 13.4**

 `using FFTW`
 │ Package FFTW not found, but a package named FFTW is available from a registry. 
 │ Install package?
 │   (@v1.9) pkg> add FFTW 
 └ (y/n/o) [y]: y
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
  [7a1cc6ca] + FFTW v1.7.1
    Updating `~/.julia/environments/v1.9/Manifest.toml`
  [621f4979] + AbstractFFTs v1.3.2
  [7a1cc6ca] + FFTW v1.7.1
  [f5851436] + FFTW_jll v3.3.10+0
  [1d5cc7b8] + IntelOpenMP_jll v2023.1.0+0
  [856f044c] + MKL_jll v2023.1.0+0
[ Info: Precompiling FFTW [7a1cc6ca-52ef-59f5-83cd-3a7055c09341]
ERROR: LoadError: UndefVarError: `libmkl_rt_path` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/FFTW/HfEjB/src/providers.jl:86
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [4] include(x::String)
   @ FFTW ~/.julia/packages/FFTW/HfEjB/src/FFTW.jl:1
 [5] top-level scope
   @ ~/.julia/packages/FFTW/HfEjB/src/FFTW.jl:17
 [6] include
   @ ./Base.jl:457 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2045
 [8] top-level scope
   @ stdin:3
in expression starting at /Users/lixi307/.julia/packages/FFTW/HfEjB/src/providers.jl:84
in expression starting at /Users/lixi307/.julia/packages/FFTW/HfEjB/src/FFTW.jl:1
in expression starting at stdin:3
ERROR: Failed to precompile FFTW [7a1cc6ca-52ef-59f5-83cd-3a7055c09341] to "/Users/lixi307/.julia/compiled/v1.9/FFTW/jl_HmZkkA".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2296
 [3] compilecache
   @ ./loading.jl:2163 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1805
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1660
 [6] macro expansion
   @ ./loading.jl:1648 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1611

**Comment by giordano** [comment] 2023-07-02 20:23
Your problem is completely unrelated to the present issue, please open a new ticket.

Anyway the gist is that MKL isn't available for your processor, but why this is happening is a problem that we can't look at here.
