### ISSUE TITLE
MKL: FFTW could not create plan

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaMath/FFTW.jl#252] opened 2022-10-07 22:52 UTC
Hi everyone,
certain ffts with the MKL package throw error messages. The minimum working example is:

```
using FFTW
FFTW.set_provider!("mkl")
```
Restart Julia
```
using FFTW
x = randn(ComplexF32, 10,10,64,64);
fft!(x, 3:ndims(x))
```
which throws this error message:
```
ERROR: FFTW could not create plan
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] macro expansion
   @ ~/.julia/packages/FFTW/sfy1o/src/fft.jl:600 [inlined]
 [3] (FFTW.cFFTWPlan{ComplexF32, -1, true, 4})(X::Array{ComplexF32, 4}, Y::Array{ComplexF32, 4}, region::UnitRange{Int64}, flags::UInt32, timelimit::Float64)
   @ FFTW ~/.julia/packages/FFTW/sfy1o/src/FFTW.jl:49
 [4] #plan_fft!#8
   @ ~/.julia/packages/FFTW/sfy1o/src/fft.jl:733 [inlined]
 [5] plan_fft!
   @ ~/.julia/packages/FFTW/sfy1o/src/fft.jl:723 [inlined]
 [6] fft!(x::Array{ComplexF32, 4}, region::UnitRange{Int64})
   @ AbstractFFTs ~/.julia/packages/AbstractFFTs/Wg2Yf/src/definitions.jl:63
 [7] top-level scope
   @ REPL[10]:1
```
I am using Julia 1.8.1 and FFTW v1.5.0. 

The error occurs both with 32 and 64 bit floats. It does not occur, if I perform the FFT, e.g., over the dimensions `2:ndims(x)`. 

Thanks for your help!

**Comment by stevengj** [comment] 2022-10-08 00:50
Duplicate of #242.  Use the real FFTW library, and complain to Intel.

**Closed by stevengj** 2022-10-08 00:50 UTC

**Comment by JakobAsslaender** [comment] 2022-10-08 01:12
Apologies for creating a duplicate. The only reason why I am using MKL is because I get segfaults with FFTW (issue #236)--otherwise I am a huge fan of FFTW, thanks for implementing it!
